---
title: "conditionals & loops"
author: "Meagan Brown"
date: '2022-08-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

### Load Libraries

```{r}
library(tidyverse)
library(palmerpenguins)
```

### `if` statements

```{r}
burrito <- 3

if (burrito > 2) {
  print("I love burritos") 
  }

```

```{r}
my_ships <- c("Millenium Falcon", 
              "X-wing", 
              "Tie Fighter", 
              "Death Star")

str_detect(my_ships, 
           pattern = "X")

# help me ask questions about what is in a phrase

phrase <- "I love burritos"

if(str_detect(phrase, "love")){
  print("I am a burrito fan.")
}
```

```{r}
tatooine_characters <- starwars %>% 
  filter(homeworld == "Tatooine") 

# Use %in% operator to check for multiple positive matches

tatooine_endor_naboo_char <- starwars %>% 
  filter(homeworld %in% c("Tatooine", "Naboo", "Endor"))
  

```

### `if-else` statement

```{r}
pika <- 89.1

if (pika > 60){
  print("mega pika")
} else {
  print("normal pika")
}
```

```{r}
marmot <- 2.8

if(marmot < 0.5){
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3 ) {
  print("this is a medium marmot")
} else {
  print("this is a large marmot")
}
```

# `group_by()` %>% summarize()
```{r}
species_length <- penguins %>% 
  group_by(species, island) %>% 
  summarize(mean_bill_length = mean(bill_length_mm, 
                                na.rm = TRUE),
            sd_bill_length = sd(bill_length_mm, 
                                na.rm = TRUE),
            n = n())


# find the mean and sd of character height in starwars grouped by homeworld and the 

starwars_height <- starwars %>% 
  group_by(homeworld) %>% 
  summarize(mean_height = mean(height, 
                               na.rm = TRUE), 
            sd_height = sd(height, 
                           na.rm = TRUE))

# max and min flipper length and sample size for each species of penguins
penguin_max_min <- penguins %>% 
  group_by(species, sex) %>% 
  summarize(max_length_mm = max(flipper_length_mm, 
                                na.rm = TRUE),
            min_length_mm = min(flipper_length_mm, 
                                na.rm = TRUE),
            sample_size = n())

#across
penguins %>% 
  group_by(species) %>% 
  summarize(across(where(is.numeric), 
                   mean, 
                   na.rm = TRUE))
```

```{r}
##For loop - cumulative calculations
tree_height <- c(1, 2, 6 , 10, 14, 20) 

for (i in seq_along(tree_height)) {
  val = tree_height[i] + tree_height[i + 1]
  print(val)
}

# for loop with a conditional statement
animal_ages <- vector(mode = "numeric", 
                      length = length(species))

species <- c("dog", "elephant", "goat", "dog", "dog", "elephant")

age_human <- c(3, 8, 4, 6, 12, 18)

for (i in seq_along(species)) {
  if(species[i] == "dog") {
    animal_age <- age_human[i] * 7
  } else if (species[i] == "elephant") {
    animal_age <- age_human[i] * 0.88
  } else if (species[i] == "goat") {
    animal_age <- age_human[i] * 4.7
  } 
  animal_ages[i] <- animal_age
}
```

### For loops across data frames

```{r}
mean_mtcars <- vector(mode = "numeric", length = ncol(mtcars))

for (i in seq_along(mean_mtcars)) {
  mean_val <- mean(mtcars[[i]], na.rm = TRUE)
  mean_mtcars[i] <- mean_val
} 

mean_mtcars
```

### Adding syntactic sugar #apply #across #map_df

```{r}
apply(X = mtcars, MARGIN = 2, FUN = mean)
```

```{r}
map(.x = mtcars, .f = mean)

purr_sum <- map_df(.x = mtcars, .f = mean)
```

